### ISSUE TITLE
Section: Getting Started

### ISSUE THREAD

**Issue by bvreede** [esciencecenter-digital-skills/lesson-R-packaging#3]
- [x] Create a basic package 
    - File > new project > new directory > R package
    - Choose a name (`mysterycoffee`)
    - Tick the box for ‘git repo’, but leave ‘renv’ empty 
- [x] Discuss the package that was created 
    - DESCRIPTION
    - R folder: hello.R 
- [x] <del> Create first documentation with Roxygen </del> Strikethrough items have been moved to their own sections
    - <del> Delete man folder </del>
    - <del> Delete NAMESPACE </del>
    - <del> Insert Roxygen Skeleton (ctrl+alt+shift+R) </del>
    - <del> Edit basic skeleton </del>
    - <del> Edit the function: </del>
        - <del> Take parameter ‘name’ </del>
        - <del> Return instead of print paste(“hello”, name) </del>
    - <del> Insert Roxygen Skeleton and watch the change (@param is added)  </del>
- [x] <del>Use the function </del>
    - <del>Try and fail to use the function </del>
    - <del>Install and restart (ctrl+shift+b) </del>
    - <del>Succeed in using the function hello(“yourname”) </del>
    - <del>Show the help with ?hello </del>
- [x] <del> Add the `mysterycoffee::make_group()` function </del>
- [x] Automate documentation
    - Build tab > More > (configure) build tools
    - Tick ‘Generate documentation with Roxygen’
    - Configure > tick all boxes except vignette
    - Run documentation (ctrl + shift + d)
    - Build (ctrl + shift + b) and show that documenting is automatic

**Comment by PabRod** [comment]
I am assuming we'll introduce the `usethis` package in this chapter. Please let me know if that's not the case, @bvreede.

**Comment by PabRod** [comment]
From a pedagogical point of view, it is quite painful to introduce `roxygen2` at this point. I don't see an easy way around it, but it is worth thinking of it.

**Comment by PabRod** [comment]
Just merged to `gh-pages` for the rendering.

**Comment by PabRod** [comment]
We have a first version 🎉
