### ISSUE TITLE
getting started: what does build and install mean?

### ISSUE THREAD

**Issue by liekelotte** [esciencecenter-digital-skills/lesson-R-packaging#39]
if one of the takeaways from this episode is that a package is no more than a folder structure, what does pressing "install", actually "do"? is it just saving the package in your library? I found myself wondering this while reading the lesson.

Perhaps this could be clarified?

**Comment by PabRod** [comment]
The previous chapter, [Accessing packages](https://esciencecenter-digital-skills.github.io/lesson-R-packaging/02-accessing/index.html), elaborates on the topic of _installing_ and _attaching_. I'll take a look at it to make it more transparent.

**Comment by PabRod** [comment]
The difference between _installing_ and _attaching_ is also present in the [Glossary](https://esciencecenter-digital-skills.github.io/lesson-R-packaging/reference.html).
