### ISSUE TITLE
Section: Accessing your package

### ISSUE THREAD

**Issue by bvreede** [esciencecenter-digital-skills/lesson-R-packaging#4]
- [x] Local access: use the package in another project 
    - Access it from another R project
- [x] Remote access
    - Download from CRAN
    - Download and install with via devtools with a remote repository (include demo with a simple package, for instance [babynames](https://github.com/hadley/babynames))
- [x] Attach and use
    - Load the package with library()
    - Use the package’s functions

**Comment by PabRod** [comment]
I am polishing this chapter, and I am struggling with the order. I think this may be more natural, as it builds up from more to less familiar:

1. Install from CRAN
2. Attach the package and use it
3. Other ways to install
    1. Install locally
    2. Install from GitHub 

Subsection 3.ii may even be postponed until we talk about GitHub.

What do you think @bvreede?

**Comment by PabRod** [comment]
Still needs review.

**Comment by PabRod** [comment]
We have a first version 🎉
