### ISSUE TITLE
Description file could use a little more explanation

### ISSUE THREAD

**Issue by liekelotte** [esciencecenter-digital-skills/lesson-R-packaging#40]
How do you know what the version is? Who should be part of the maintainer field? Do we need to pay attention to the encoding? 

Also, there's a FIXME in the exercise about the License field. Can it be fixed?

**Comment by PabRod** [comment]
About the FIXME:

Our original plan was to write an episode about licensing. This was later discarded.

**Comment by PabRod** [comment]
Close with e053993ac245328cd7297d045fe2be05e634d1f5.

Nevertheless... it could be a good idea to add **some** license (most likely Apache) without many explanations (issue #48).
