### ISSUE TITLE
Why are we not attaching usethis? 

### ISSUE THREAD

**Issue by liekelotte** [esciencecenter-digital-skills/lesson-R-packaging#43]
We're calling use_test() from `usethis`, without explaining what that package does. Participants also don't know yet why you aren't attaching it. It's worth metioning this here, I think.

**Comment by PabRod** [comment]
Side idea: consider relegating `usethis` to a footnote.

**Comment by PabRod** [comment]
Good question. No idea. I have always done it that way and seems to be a good practice... but I lack a convincing explanation.

**Comment by PabRod** [comment]
Twitter + RStats tag to the rescue!
https://twitter.com/DonMostrenco/status/1494663567055986691

**Comment by PabRod** [comment]
The reason seems to be that it is advisable to attach as few packages as possible during the development of a package, in order to keep our environment as isolated as possible.
