### ISSUE TITLE
Section: Version control

### ISSUE THREAD

**Issue by bvreede** [esciencecenter-digital-skills/lesson-R-packaging#5]
- [ ] Configure SSH
  - Tools > Global options > Git/SVN (Linux)
  - Preferences > Git/SVN (Mac)
  - Set the private key in the dialog
  - Copy the public key
  - Store it on GitHub
  - Check function with ssh git@github.com on shell (access via Rstudio)?
- [ ] Connect the local repository to a remote repository
  - Create the remote repository and keep it empty
  - Git tab > ‘branch’ button (purple) > ‘add remote’
  - Name: origin
  - Address: copied SSH address from remote repository
  - Branch name: main
- [ ] Commit and push content of the repository
- [ ] Refresh the remote GitHub
- [ ] Put instructions for install + use in the ReadMe?
- [ ] Go through a few cycles of edit > commit > push?

**Comment by PabRod** [comment]
We decided to remove this from this course in favor of modularity.
